'use client'

import { useEffect, useMemo, useState } from 'react'
import { BookOpen, Check, ChevronRight, Dumbbell, Footprints, Moon, Move3d, Play, Utensils, BriefcaseBusiness } from 'lucide-react'
import { challengeDays, challengeTotalDays, formatToday, getChallengeDay, getChallengeStatus, getDayState, phaseColors, type Activity as ActivityType, type ChallengeDay } from '@/data/challenge'
import { dietDays, dietPlan, getDietDay, getDietTemplate, type DietDay } from '@/data/diet'
import './challenge.css'

const icons = { walk: Footprints, mobility: Move3d, strength: Dumbbell, reading: BookOpen, sleep: Moon, work: BriefcaseBusiness, food: Utensils }

function Header({ currentDay }: { currentDay: number }) {
  return <header className="challenge-header"><div><p className="eyebrow">RETO {challengeTotalDays} <span className="eyebrow-dot" /></p><h1>Buenos días.</h1><p className="today-label">{formatToday()} · Día {currentDay} de {challengeTotalDays}</p></div><button className="avatar-button" aria-label="Abrir perfil">PL8</button></header>
}

function ProgressCard({ currentDay }: { currentDay: number }) {
  const progress = Math.round((currentDay / challengeTotalDays) * 100)
  return <section className="progress-card"><div className="progress-top"><div><p className="card-kicker">TU PROGRESO</p><strong>Día {currentDay} <span>/ {challengeTotalDays}</span></strong></div><span className="progress-percent">{progress}%</span></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><p className="progress-note">{currentDay === challengeTotalDays ? 'Has llegado al cierre. Quédate con lo que funciona.' : 'Un día cada vez. La constancia es el objetivo.'}</p></section>
}

function DayPicker({ currentDay, selectedDay, onSelect }: { currentDay: number; selectedDay: number; onSelect: (day: number) => void }) {
  return <section className="day-picker-wrap"><div className="section-heading"><div><p className="card-kicker">TU PLAN</p><h2>{challengeTotalDays} días para volver a moverte</h2></div><span className="day-count">{currentDay}/{challengeTotalDays}</span></div><div className="day-picker" role="tablist" aria-label="Seleccionar día del reto">{challengeDays.map((item) => { const state = getDayState(item.day, currentDay); return <button key={item.day} role="tab" aria-selected={selectedDay === item.day} className={`day-pill day-${state} ${selectedDay === item.day ? 'selected' : ''}`} onClick={() => onSelect(item.day)}><span>Día</span><strong>{item.day}</strong>{state === 'done' && <Check size={12} aria-label="Completado" />}{state === 'current' && <i aria-hidden="true" />}</button> })}</div></section>
}

function ActivityRow({ activity }: { activity: ActivityType }) { const Icon = icons[activity.kind]; return <div className="activity-row"><div className={`activity-icon activity-${activity.kind}`}><Icon size={18} strokeWidth={2.2} /></div><div className="activity-copy"><strong>{activity.title}</strong><span>{activity.detail}</span></div><ChevronRight className="activity-arrow" size={17} /></div> }

function ExerciseList({ exercises }: { exercises: NonNullable<ChallengeDay['exercises']> }) { return <div className="exercise-list">{exercises.map((exercise) => <div className="exercise-row" key={exercise.name}><span>{exercise.name}</span><strong>{exercise.reps}</strong></div>)}</div> }

function DayDetail({ day }: { day: ChallengeDay }) { return <section className="detail-section"><div className="detail-header"><div><span className={`phase-tag phase-${phaseColors[day.phase]}`}>{day.phase}</span><h2>{day.title}</h2><p>{day.intro}</p></div><div className="day-number">{String(day.day).padStart(2, '0')}</div></div><div className="goal-card"><div className="goal-icon"><Play size={16} fill="currentColor" /></div><div><span>OBJETIVO DEL DÍA</span><strong>{day.goal}</strong></div><div className="goal-steps"><strong>{day.steps}</strong><span>pasos aprox.</span></div></div><div className="activities"><div className="subheading"><h3>Tu día</h3><span>{day.activities.length} momentos</span></div>{day.activities.map((activity) => <ActivityRow key={activity.title} activity={activity} />)}</div>{day.exercises && <div className="strength-card"><div className="subheading"><h3>Circuito</h3><span>Sin gimnasio</span></div><ExerciseList exercises={day.exercises} /></div>}{day.reflection && <div className="reflection-card"><div className="subheading"><h3>Tu evaluación</h3><span>1–10</span></div>{day.reflection.map((item) => <div className="reflection-row" key={item}><span>{item}</span><b>/10</b></div>)}</div>}</section> }

function DietDayPicker({ selectedDay, onSelect }: { selectedDay: number; onSelect: (day: number) => void }) { return <section className="day-picker-wrap"><div className="section-heading"><div><p className="card-kicker">TU PLAN</p><h2>Primeros 15 días de dieta</h2></div><span className="day-count">{selectedDay}/15</span></div><div className="day-picker" role="tablist" aria-label="Seleccionar día de dieta">{dietDays.map((item) => <button key={item.day} role="tab" aria-selected={selectedDay === item.day} className={`day-pill ${selectedDay === item.day ? 'selected' : ''}`} onClick={() => onSelect(item.day)}><span>Día</span><strong>{item.day}</strong></button>)}</div></section> }

function DietMeal({ meal }: { meal: { name: string; time: string; description: string } }) { return <article className="diet-meal"><div className="diet-meal-heading"><div><h3>{meal.name}</h3><span>{meal.time}</span></div><Utensils size={18} /></div><p>{meal.description}</p></article> }

function DietDetail({ day }: { day: DietDay }) { const template = getDietTemplate(day.day); return <section className="diet-section"><div className="detail-header"><div><span className="phase-tag phase-mint">{template.label}</span><h2>{day.focus}</h2><p>Menú cerrado para el día {day.day} · {day.date}.</p></div><div className="day-number">{String(day.day).padStart(2, '0')}</div></div><div className="diet-macros"><div className="diet-macros-heading"><strong>MACROS DEL DÍA</strong><span>Objetivo diario</span></div><div className="macro-grid"><div className="macro-item"><strong>{day.macros.calories}</strong><span>Calorías</span></div><div className="macro-item"><strong>{day.macros.protein}</strong><span>Proteína</span></div><div className="macro-item"><strong>{day.macros.carbohydrates}</strong><span>Hidratos</span></div><div className="macro-item"><strong>{day.macros.fats}</strong><span>Grasas</span></div></div><p>Valores estimados del menú cerrado de este día.</p></div><div className="diet-notice"><strong>Objetivo del día</strong><span>{day.focus}</span></div><div className="diet-meals">{template.meals.map((meal) => <DietMeal key={meal.name} meal={meal} />)}</div><div className="diet-protocol"><div className="subheading"><h3>Hábitos diarios</h3><span>Todos los días</span></div>{dietPlan.dailyProtocol.map((item) => <p key={item}>{item}</p>)}</div></section> }

export function ChallengeApp() { const [currentDay, setCurrentDay] = useState(1); const [selectedDay, setSelectedDay] = useState(1); const [activeView, setActiveView] = useState<'routine' | 'diet'>('routine'); useEffect(() => { const day = getChallengeDay(); setCurrentDay(day); setSelectedDay(day); if ('serviceWorker' in navigator && process.env.NODE_ENV === 'production') navigator.serviceWorker.register('/sw.js').catch(() => {}) }, []); const day = useMemo(() => challengeDays[selectedDay - 1] ?? challengeDays[0], [selectedDay]); const dietDay = getDietDay(Math.min(selectedDay, dietDays.length)); return <main className="app-shell"><div className="app-container"><Header currentDay={currentDay} /><div className="status-line"><span className="status-dot" />{getChallengeStatus()} <span className="status-date">· Inicio 14 sep 2026</span></div><ProgressCard currentDay={currentDay} />{activeView === 'routine' ? <><DayPicker currentDay={currentDay} selectedDay={selectedDay} onSelect={setSelectedDay} /><DayDetail day={day} /></> : <><DietDayPicker selectedDay={dietDay.day} onSelect={setSelectedDay} /><DietDetail day={dietDay} /></>}</div><nav className="bottom-nav" aria-label="Navegación principal"><button className={activeView === 'routine' ? 'nav-active' : ''} onClick={() => setActiveView('routine')}><Dumbbell size={19} /><span>Rutina</span></button><button className={activeView === 'diet' ? 'nav-active' : ''} onClick={() => { setActiveView('diet'); setSelectedDay(Math.min(currentDay, dietDays.length)) }}><Utensils size={19} /><span>Dieta</span></button></nav></main> }

export default ChallengeApp

